export const URLS = {
  login: '/web/index.php/auth/login',
  dashboard: '/web/index.php/dashboard/index',
  employeeList: '/web/index.php/pim/viewEmployeeList',
  addEmployee: '/web/index.php/pim/addEmployee',
  addCandidate: '/web/index.php/recruitment/addCandidate',
  candidateList: '/web/index.php/recruitment/viewCandidates',
  systemUserList: '/web/index.php/admin/viewSystemUsers',
  reviewSearch: '/web/index.php/performance/searchPerformanceReview',
  directory: '/web/index.php/directory/viewDirectory',
  addCustomer: '/web/index.php/time/addCustomer',
  customerList: '/web/index.php/time/viewCustomers',
  applyLeave: '/web/index.php/leave/applyLeave',
  myLeaveList: '/web/index.php/leave/viewMyLeaveList',
  leaveList: '/web/index.php/leave/viewLeaveList',
  leaveEntitlements: '/web/index.php/leave/viewLeaveEntitlements',
  submitClaim: '/web/index.php/claim/submitClaim',
  myClaims: '/web/index.php/claim/viewClaim',
  buzz: '/web/index.php/buzz/viewBuzz',
} as const;

export const API = {
  pimEmployees: '/web/index.php/api/v2/pim/employees',
  adminUsers: '/web/index.php/api/v2/admin/users',
  recruitmentCandidates: '/web/index.php/api/v2/recruitment/candidates',
  timeCustomers: '/web/index.php/api/v2/time/customers',
  claimRequests: '/web/index.php/api/v2/claim/requests',
  claimRequestAction: (id: number) => `/web/index.php/api/v2/claim/requests/${id}/action`,
  claimEvents: '/web/index.php/api/v2/claim/events',
  leaveRequests: '/web/index.php/api/v2/leave/leave-requests',
  leaveRequest: (id: number) => `/web/index.php/api/v2/leave/leave-requests/${id}`,
  leavePeriod: '/web/index.php/api/v2/leave/leave-period',
  leavePeriods: '/web/index.php/api/v2/leave/leave-periods',
  leaveEntitlements: '/web/index.php/api/v2/leave/leave-entitlements',
  leaveTypes: '/web/index.php/api/v2/leave/leave-types',
  buzzPosts: '/web/index.php/api/v2/buzz/posts',
  timeSheetPeriod: '/web/index.php/api/v2/time/time-sheet-period',
} as const;
